// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZ6yXv9hFnrCX2bKavm0rXS5P7HXUbp8',
    appId: '1:561592722441:web:f7c287c33556d7879144d8',
    messagingSenderId: '561592722441',
    projectId: 'fir-fullapp-46e71',
    authDomain: 'fir-fullapp-46e71.firebaseapp.com',
    storageBucket: 'fir-fullapp-46e71.appspot.com',
    measurementId: 'G-XW5LT9CYMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKpV5Ke-zKSHKI5uth7tukbHHpQsKp_P0',
    appId: '1:561592722441:android:628ed47bfb461e399144d8',
    messagingSenderId: '561592722441',
    projectId: 'fir-fullapp-46e71',
    storageBucket: 'fir-fullapp-46e71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFdsaDI1L6iA6fA7jx7LwccEHYWDCdkc',
    appId: '1:561592722441:ios:9b44dba85c62d0e29144d8',
    messagingSenderId: '561592722441',
    projectId: 'fir-fullapp-46e71',
    storageBucket: 'fir-fullapp-46e71.appspot.com',
    iosBundleId: 'com.example.firebasefullapp',
  );
}
